title:             Mice on Vacation
email:             bojan.valentinacamelia@gmail.com
description:       TODO
author:            Valentina Bojan
baseurl:           ''
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  TBD
github_username:   TBD
facebook_username: TBD

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate